from obqa.allennlp_custom.modules.similarity_functions.linear_extended_feedforward import LinearExtendedFeedForwardReprCombination
from obqa.allennlp_custom.modules.similarity_functions.linear_extended import LinearExtenedSimilarity
from obqa.allennlp_custom.modules.similarity_functions.linear_transform_sum_repr_combination import LinearTransformSumReprCombination
from obqa.allennlp_custom.modules.similarity_functions.weighted_sum_repr_combination import WeightedSumReprCombination
